# Generated by Django 2.2.24 on 2025-01-21 18:47

from django.db import migrations
import phonenumbers


def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats:
        raw_phone = flat.owners_phonenumber

        try:
            parsed_phone = phonenumbers.parse(raw_phone, "RU")
            if phonenumbers.is_valid_number(parsed_phone):
                flat.owner_pure_phone = phonenumbers.format_number(
                    parsed_phone, phonenumbers.PhoneNumberFormat.E164
                )
            else:
                flat.owner_pure_phone = None
        except phonenumbers.NumberParseException:
            flat.owner_pure_phone = None

        flat.save()


def revert_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone, revert_owner_pure_phone),
    ]