# Generated by Django 2.2.24 on 2025-01-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_transfer_flat_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
